services:
  tg-hubitat-bot:
    image: jbaru.ch/tg-hubitat-bot:${TAG:-latest}
    container_name: jbaru.ch_tg-hubitat-bot-1
    restart: unless-stopped
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      MAKER_API_APP_ID: ${MAKER_API_APP_ID}
      MAKER_API_TOKEN: ${MAKER_API_TOKEN}
      CHAT_ID: ${CHAT_ID:-}
      DEFAULT_HUB_IP: ${DEFAULT_HUB_IP:-hubitat.local}
